python main.py --exp=joint_cl_exp --semi_split=10 --dataset=MUTAG --save=joint_cl_exp --epochs=30 --batch_size=128 --lr=0.01
python main.py --exp=joint_cl_exp --semi_split=10 --dataset=PROTEINS --save=joint_cl_exp --epochs=30 --batch_size=128 --lr=0.01
python main.py --exp=joint_cl_exp --semi_split=10 --dataset=NCI1 --save=joint_cl_exp --epochs=30 --batch_size=128 --lr=0.01
python main.py --exp=joint_cl_exp --semi_split=10 --dataset=IMDB-BINARY --save=joint_cl_exp --epochs=30 --batch_size=128 --lr=0.01
python main.py --exp=joint_cl_exp --semi_split=10 --dataset=COLLAB --save=joint_cl_exp --epochs=30 --batch_size=64 --lr=0.01
python main.py --exp=joint_cl_exp --semi_split=10 --dataset=DD --save=joint_cl_exp  --epochs=30 --batch_size=64 --lr=0.01
python main.py --exp=joint_cl_exp --semi_split=10 --dataset=REDDIT-BINARY --save=joint_cl_exp --epochs=30 --batch_size=64 --lr=0.01
python main.py --exp=joint_cl_exp --semi_split=10 --dataset=github_stargazers --save=joint_cl_exp --epochs=30 --batch_size=64 --lr=0.01
python main.py --exp=joint_cl_exp --semi_split=10 --dataset=REDDIT-MULTI-5K --save=joint_cl_exp --epochs=30 --batch_size=64 --lr=0.01